/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 15-Thg11-2019 10:24:24 SA 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `attr` CASCADE
;

DROP TABLE IF EXISTS `category` CASCADE
;

DROP TABLE IF EXISTS `comment` CASCADE
;

DROP TABLE IF EXISTS `post` CASCADE
;

DROP TABLE IF EXISTS `product` CASCADE
;

DROP TABLE IF EXISTS `product_attr` CASCADE
;

DROP TABLE IF EXISTS `product_category` CASCADE
;

DROP TABLE IF EXISTS `user` CASCADE
;

/* Create Tables */

CREATE TABLE `attr`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`key` VARCHAR(50) NULL,
	`value` VARCHAR(50) NULL,
	CONSTRAINT `PK_attr` PRIMARY KEY (`id` ASC)
);

CREATE TABLE `category`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(50) NULL,
	`isslide` smallint(2) NULL,
	CONSTRAINT `PK_category` PRIMARY KEY (`id` ASC)
);

CREATE TABLE `comment`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`product_id` INT NOT NULL,
	`user_id` INT NULL,
	`content` VARCHAR(50) NULL,
	`rate` INT NULL,
	`time` VARCHAR(50) NOT NULL,
	CONSTRAINT `PK_comment` PRIMARY KEY (`id` ASC)
);

CREATE TABLE `post`
(
	`post_id` INT NOT NULL AUTO_INCREMENT,
	`post_title` VARCHAR(50) NULL,
	`post_content` VARCHAR(50) NULL,
	`post_publish` DATETIME NULL,
	`post_update` DATETIME NULL,
	`post_` VARCHAR(50) NULL,
	CONSTRAINT `PK_post` PRIMARY KEY (`post_id` ASC)
)

;

CREATE TABLE `product`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(50) NULL,
	`price_sale` FLOAT NULL,
	`price_original` FLOAT NULL,
	`alias` VARCHAR(50) NULL,
	`url_images` VARCHAR(2000) NULL,
	`post_id` INT NULL,
	CONSTRAINT `PK_product` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `product_attr`
(
	`product_id` INT NOT NULL,
	`attr_id` INT NOT NULL,
	CONSTRAINT `PK_attr` PRIMARY KEY (`attr_id` ASC, `product_id` ASC)
)

;

CREATE TABLE `product_category`
(
	`product_id` INT NOT NULL,
	`category_id` INT NOT NULL,
	CONSTRAINT `PK_product_category` PRIMARY KEY (`product_id` ASC, `category_id` ASC)
)

;

CREATE TABLE `user`
(
	`id` INT NOT NULL,
	`name` VARCHAR(30) NULL,
	`age` INT NULL,
	`sex` BIT(1) NULL,
	`email` VARCHAR(30) NULL,
	`phone_number` VARCHAR(20) NULL,
	CONSTRAINT `PK_user` PRIMARY KEY (`id` ASC)
)

;

/* Create Foreign Key Constraints */

ALTER TABLE `comment` 
 ADD CONSTRAINT `FK_comment_product`
	FOREIGN KEY (`product_id`) REFERENCES `product` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `comment` 
 ADD CONSTRAINT `FK_comment_user`
	FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `product` 
 ADD CONSTRAINT `FK_product_post`
	FOREIGN KEY (`post_id`) REFERENCES `post` (`post_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `product_attr` 
 ADD CONSTRAINT `FK_product_attr_attr`
	FOREIGN KEY (`attr_id`) REFERENCES `attr` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `product_attr` 
 ADD CONSTRAINT `FK_product_attr_product`
	FOREIGN KEY (`product_id`) REFERENCES `product` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `product_category` 
 ADD CONSTRAINT `FK_product_category_category`
	FOREIGN KEY (`category_id`) REFERENCES `category` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `product_category` 
 ADD CONSTRAINT `FK_product_category_product`
	FOREIGN KEY (`product_id`) REFERENCES `product` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1 
;
